# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 341, 601))
        self.tableView.setObjectName("tableView")
        self.riseButton = QtWidgets.QPushButton(self.centralwidget)
        self.riseButton.setGeometry(QtCore.QRect(360, 10, 61, 23))
        self.riseButton.setObjectName("riseButton")
        self.lowButton = QtWidgets.QPushButton(self.centralwidget)
        self.lowButton.setGeometry(QtCore.QRect(360, 40, 61, 23))
        self.lowButton.setObjectName("lowButton")
        self.tableView2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView2.setGeometry(QtCore.QRect(380, 550, 851, 91))
        self.tableView2.setObjectName("tableView2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(380, 450, 211, 81))
        self.groupBox.setObjectName("groupBox")
        self.num_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.num_radioButton.setGeometry(QtCore.QRect(10, 20, 71, 28))
        self.num_radioButton.setObjectName("num_radioButton")
        self.rate_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.rate_radioButton.setGeometry(QtCore.QRect(10, 50, 71, 28))
        self.rate_radioButton.setChecked(True)
        self.rate_radioButton.setObjectName("rate_radioButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(90, 20, 91, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.adjustButton = QtWidgets.QPushButton(self.groupBox)
        self.adjustButton.setGeometry(QtCore.QRect(90, 50, 91, 23))
        self.adjustButton.setObjectName("adjustButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(430, 10, 791, 401))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.search_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_lineEdit.setGeometry(QtCore.QRect(10, 10, 341, 20))
        self.search_lineEdit.setObjectName("search_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionClose)
        self.menu_2.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.riseButton.setText(_translate("MainWindow", "升序"))
        self.lowButton.setText(_translate("MainWindow", "降序"))
        self.groupBox.setTitle(_translate("MainWindow", "调整"))
        self.num_radioButton.setText(_translate("MainWindow", "及格分数"))
        self.rate_radioButton.setText(_translate("MainWindow", "及格比例"))
        self.adjustButton.setText(_translate("MainWindow", "调整"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menu_2.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Alt+O"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionNew.setShortcut(_translate("MainWindow", "Alt+N"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Alt+C"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

